name: Combine

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  my_job:
    runs-on: ubuntu-18.04

    steps:
      - name: Step 1
        id: job1
        run: |
          echo "Running Step 1"
          # Add your Step 1 logic here

      - name: Step 2
        if: ${{ job.status == 'success' }}
        run: |
          echo "Running Step 2"
          # Add your Step 2 logic here
